name: Graphs CI
on:
  schedule:
    - cron: "0 * * * *"
  repository_dispatch:
    types: [graphs]
  workflow_dispatch:
permissions: write-all
jobs:
  release:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}
      - uses: upptime/uptime-monitor@v1.43.13
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
